apiVersion: v1
kind: Service
metadata:
  name: jenkins-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
